import type { NextPage } from 'next'
import Head from 'next/head'
import { MouseEventHandler } from 'react'

import { ThemeTypes } from '@/@types/view'
import Layout from '@/components/layouts/Layout'
import { Hero } from '@/components/sections/Hero'

type Props = {
  toggleTheme: MouseEventHandler<HTMLButtonElement>
  currentTheme: ThemeTypes
}

const Home: NextPage<Props> = ({ toggleTheme, currentTheme }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout toggleTheme={toggleTheme} currentTheme={currentTheme}>
        <Hero />
      </Layout>
    </>
  )
}

export default Home
