import { Container } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'

import Layout from '@/components/layouts/Layout'
import styles from '@/styles/Home.module.css'

import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>main</Layout>
    </>
  )
}

export default Home
